/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hmsdevelopment.teachingassistant;

/**
 *
 * @author stephen.r.brayson
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(boolean authError) {
        initComponents();
        if (!authError) {
            errorMessage.setVisible(false);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();
        loginHeader = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 64, 89));
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setName("Login Screen"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(204, 51, 0));
        exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 50, 40));

        errorMessage.setBackground(new java.awt.Color(253, 229, 215));
        errorMessage.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(168, 67, 5));
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setText("username or password incorrect");
        errorMessage.setOpaque(true);
        getContentPane().add(errorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 62));

        loginHeader.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 128)); // NOI18N
        loginHeader.setForeground(new java.awt.Color(255, 253, 237));
        loginHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHeader.setText("Login");
        getContentPane().add(loginHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 180, -1, 197));

        username.setBackground(new java.awt.Color(255, 253, 237));
        username.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 56)); // NOI18N
        username.setForeground(new java.awt.Color(34, 34, 34));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("username");
        username.setBorder(null);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 497, 628, 78));

        password.setBackground(new java.awt.Color(255, 253, 237));
        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 56)); // NOI18N
        password.setForeground(new java.awt.Color(34, 34, 34));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("*********");
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 593, 628, -1));

        submit.setBackground(new java.awt.Color(240, 123, 63));
        submit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 253, 237));
        submit.setText("submit");
        submit.setBorder(null);
        submit.setBorderPainted(false);
        submit.setContentAreaFilled(false);
        submit.setOpaque(true);
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 690, 420, 60));

        background.setBackground(new java.awt.Color(45, 64, 89));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 34, 34), 5));
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton exit;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JTextField password;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
